- name: Disable selinux
  become: yes
  selinux:
    state: disabled
  register: selinux_info
- name: Reboot the computer to disable selinux
  when: selinux_info.reboot_required == true
  become: yes
  reboot:    
- name: Download NodeJS repo file
  get_url:
    url: https://rpm.nodesource.com/setup_14.x
    dest: /tmp/install_node_script
  register: nodejs_setup_task
- name: Run the NodeJS install script
  when: nodejs_setup_task.changed
  become: yes
  shell: bash /tmp/install_node_script
- name: Installing packages...
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - nginx
    - nodejs
    - firewalld
- name: Make sure app can be written
  become: yes
  file:
    path: "{{ frontend_app_path }}"
    state: directory
    owner: "{{ frontend_user }}"
- name: Make sure the static files are available locally
  become: yes
  become_user: "{{ frontend_user }}"
  git:
    repo: https://github.com/bezkoder/react-crud-web-api.git
    dest: "{{ frontend_app_path }}"
    force: yes
- name: Changing the http-common.js
  become: yes
  replace:
    path: "{{ frontend_app_path }}/src/http-common.js"
    regexp: 'http://localhost:8080/api'
    replace: '/api'
- name: Make sure the front end dependencies are installed
  become: yes
  become_user: "{{ frontend_user }}"
  shell: npm install
  args:
    chdir: "{{ frontend_app_path }}"
- name: Build the static files
  become: yes
  become_user: "{{ frontend_user }}"
  shell: npm run-script build
  args:
    chdir: "{{ frontend_app_path }}"
- name: Provision nginx.conf
  become: yes
  template: 
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf_task
- name: Make sure nginx is started and enabled
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: Make sure nginx is restarted if config file changed
  become: yes
  when: nginx_conf_task.changed
  systemd:
    name: nginx
    state: restarted
